---
title: "<tt>matsindf</tt> Vignette"
author: "Matthew Kuperus Heun"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{matsindf Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


Data frames of matrices, 
such as those created by <tt>matsindf</tt>,
are like magic spreadsheets 
in which single cells contain entire matrices.



## Suggested workflow

A suggested analysis workflow is as follows:

* Munge data into tidy data frame with columns for matrix name, 
row name, column name, row type, column type, and element value,
similar to <tt>tidy</tt> above.
* Use <tt>matsindf::collapse_to_matrices</tt>
to create a data frame of matrices with columns for matrix names and 
matrices themselves,
similar to <tt>mats</tt> above.
* <tt>tidyr::spread</tt> the matrices to obtain a data frame with columns for each matrix,
similar to <tt>results</tt> above.
* Perform matrix algebra operations on the columns of matrices
using <tt>byname</tt> functions.
* <tt>tidyr::gather</tt> the columns to obtain a tidy data frame of matrices.
* Use <tt>matsindf::expand_to_tidy</tt> to create a tidy data frame of matrix elements.
* <tt>tidyr::spread</tt> the data as necessary.
* Graph or perform other manipulations of the data.

